const CART_GET_DATA_PROCESSING = 'CART_GET_DATA_PROCESSING'
const CART_GET_DATA_SUCCESS = 'CART_GET_DATA_SUCCESS'
const CART_GET_DATA_FAIL = 'CART_GET_DATA_FAIL'

export {
    CART_GET_DATA_PROCESSING,
    CART_GET_DATA_SUCCESS,
    CART_GET_DATA_FAIL,
}
