const CART_GET_DATA_PROCESSING = 'CART_GET_DATA_PROCESSING'
const CART_GET_DATA_SUCCESS = 'CART_GET_DATA_SUCCESS'
const CART_GET_DATA_FAIL = 'CART_GET_DATA_FAIL'

const CART_SET_CART_INFO_SUCCESS = 'CART_SET_CART_INFO_SUCCESS'

export {
    CART_GET_DATA_PROCESSING,
    CART_GET_DATA_SUCCESS,
    CART_GET_DATA_FAIL,

    CART_SET_CART_INFO_SUCCESS,
}
