const DEVICE_GET_DATA_PROCESSING = 'DEVICE_GET_DATA_PROCESSING'
const DEVICE_GET_DATA_SUCCESS = 'DEVICE_GET_DATA_SUCCESS'
const DEVICE_GET_DATA_FAIL = 'DEVICE_GET_DATA_FAIL'

const DEVICE_ADD_DATA_PROCESSING = 'DEVICE_ADD_DATA_PROCESSING'
const DEVICE_ADD_DATA_SUCCESS = 'DEVICE_ADD_DATA_SUCCESS'
const DEVICE_ADD_DATA_FAIL = 'DEVICE_ADD_DATA_FAIL'

const STATUS = {
    ACTIVE: 'active',
    INACTIVE: 'inactive',
}
const DEVICE_TYPES = {
    BUZZER: 'BUZZER',
    FAN: 'FAN',
    GAS_SENSOR: 'GAS_SENSOR',
    LED: 'LED',
}

export {
    DEVICE_GET_DATA_PROCESSING,
    DEVICE_GET_DATA_SUCCESS,
    DEVICE_GET_DATA_FAIL,

    DEVICE_ADD_DATA_PROCESSING,
    DEVICE_ADD_DATA_SUCCESS,
    DEVICE_ADD_DATA_FAIL,

    STATUS,
    DEVICE_TYPES,
}
