const IDENTITY_GENERATE_KEY_PROCESSING = 'IDENTITY_GENERATE_KEY_PROCESSING'
const IDENTITY_GENERATE_KEY_SUCCESS = 'IDENTITY_GENERATE_KEY_SUCCESS'
const IDENTITY_GENERATE_KEY_FAIL = 'IDENTITY_GENERATE_KEY_FAIL'

const IDENTITY_PARSE_KEY_PROCESSING = 'IDENTITY_PARSE_KEY_PROCESSING'
const IDENTITY_PARSE_KEY_SUCCESS = 'IDENTITY_PARSE_KEY_SUCCESS'
const IDENTITY_PARSE_KEY_FAIL = 'IDENTITY_PARSE_KEY_FAIL'

export {
    IDENTITY_GENERATE_KEY_PROCESSING,
    IDENTITY_GENERATE_KEY_SUCCESS,
    IDENTITY_GENERATE_KEY_FAIL,

    IDENTITY_PARSE_KEY_PROCESSING,
    IDENTITY_PARSE_KEY_SUCCESS,
    IDENTITY_PARSE_KEY_FAIL,
}
