const MENU_GET_DATA_PROCESSING = 'MENU_GET_DATA_PROCESSING'
const MENU_GET_DATA_SUCCESS = 'MENU_GET_DATA_SUCCESS'
const MENU_GET_DATA_FAIL = 'MENU_GET_DATA_FAIL'

const MENU_PICK_ITEM_PROCESSING = 'MENU_PICK_ITEM_PROCESSING'
const MENU_PICK_ITEM_SUCCESS = 'MENU_PICK_ITEM_SUCCESS'
const MENU_PICK_ITEM_FAIL = 'MENU_PICK_ITEM_FAIL'

export {
    MENU_GET_DATA_PROCESSING,
    MENU_GET_DATA_SUCCESS,
    MENU_GET_DATA_FAIL,

    MENU_PICK_ITEM_PROCESSING,
    MENU_PICK_ITEM_SUCCESS,
    MENU_PICK_ITEM_FAIL,
}
