const MENU_GET_DATA_PROCESSING = 'MENU_GET_DATA_PROCESSING'
const MENU_GET_DATA_SUCCESS = 'MENU_GET_DATA_SUCCESS'
const MENU_GET_DATA_FAIL = 'MENU_GET_DATA_FAIL'

export {
    MENU_GET_DATA_PROCESSING,
    MENU_GET_DATA_SUCCESS,
    MENU_GET_DATA_FAIL,
}
