const ORDER_ADD_DATA_PROCESSING = 'ORDER_ADD_DATA_PROCESSING'
const ORDER_ADD_DATA_SUCCESS = 'ORDER_ADD_DATA_SUCCESS'
const ORDER_ADD_DATA_FAIL = 'ORDER_ADD_DATA_FAIL'

const ORDER_STATUS = {
    NEW: 'NEW',
    PREPARING: 'PREPARING',
    WAITING_REVIEW: 'WAITING_REVIEW',
    DONE: 'DONE',
}

export {
    ORDER_ADD_DATA_PROCESSING,
    ORDER_ADD_DATA_SUCCESS,
    ORDER_ADD_DATA_FAIL,

    ORDER_STATUS,
}
