const RATING_ADD_DATA_PROCESSING = 'RATING_ADD_DATA_PROCESSING'
const RATING_ADD_DATA_SUCCESS = 'RATING_ADD_DATA_SUCCESS'
const RATING_ADD_DATA_FAIL = 'RATING_ADD_DATA_FAIL'

export {
    RATING_ADD_DATA_PROCESSING,
    RATING_ADD_DATA_SUCCESS,
    RATING_ADD_DATA_FAIL,
}
