
const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS'
const USER_AUTH_PROCESSING = 'USER_AUTH_PROCESSING'
const USER_AUTH_FAIL = 'USER_AUTH_FAIL'

const USER_AUTH_SIGN_OUT_SUCCESS = 'USER_AUTH_SIGN_OUT_SUCCESS'
const USER_AUTH_SIGN_OUT_PROCESSING = 'USER_AUTH_SIGN_OUT_PROCESSING'
const USER_AUTH_SIGN_OUT_FAIL = 'USER_AUTH_SIGN_OUT_FAIL'

const USER_REGISTER_REQUEST_SUCCESS = 'USER_REGISTER_REQUEST_SUCCESS'
const USER_REGISTER_REQUEST_PROCESSING = 'USER_REGISTER_REQUEST_PROCESSING'
const USER_REGISTER_REQUEST_FAIL = 'USER_REGISTER_REQUEST_FAIL'

const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
const USER_UPDATE_PROCESSING = 'USER_UPDATE_PROCESSING'
const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL'

const USER_GET_DATA_PROCESSING = 'USER_GET_DATA_PROCESSING'
const USER_GET_DATA_SUCCESS = 'USER_GET_DATA_SUCCESS'
const USER_GET_DATA_FAIL = 'USER_GET_DATA_FAIL'

const STATUS = {
    ACTIVE: 'active',
    INACTIVE: 'inactive',
}

export {
    USER_AUTH_SUCCESS,
    USER_AUTH_PROCESSING,
    USER_AUTH_FAIL,

    USER_AUTH_SIGN_OUT_SUCCESS,
    USER_AUTH_SIGN_OUT_PROCESSING,
    USER_AUTH_SIGN_OUT_FAIL,

    USER_REGISTER_REQUEST_SUCCESS,
    USER_REGISTER_REQUEST_PROCESSING,
    USER_REGISTER_REQUEST_FAIL,

    USER_UPDATE_SUCCESS,
    USER_UPDATE_PROCESSING,
    USER_UPDATE_FAIL,

    USER_GET_DATA_PROCESSING,
    USER_GET_DATA_SUCCESS,
    USER_GET_DATA_FAIL,

    STATUS,
}
